import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Elegance Architect",
  description: "Generated by D",
  icons: {
    icon: "/fav.png", // or "/favicon.ico"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/fav.ico" />
      </head>
      <body
        className={`${inter.className} sans antialiased text-black`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
